### ISSUE TITLE
Just a suggestion

### ISSUE THREAD

**Issue by jatin-pahuja** [Mpolan16/Mpolan16.github.io_Homework_2_MPF#1]
great site I had a suggestion . 
The paragraph under about me section is too congested and looks really small while a lot of space is left unused on either of the paragraph's sides.

**Comment by Mpolan16** [comment]
Thank you! I will use that suggestion!

**Comment by Mpolan16** [comment]
I appreciate the suggestion. I just changed the about me paragraph as per your suggestion. Let me know what you think.

**Comment by jatin-pahuja** [comment]
Looks great now thanks ! 👍

**Comment by Mpolan16** [comment]
Thank you for your feedback 💯
